// Index file for Rumor Management & Fact-Checking System
// Re-exports all types and data for easier imports

// Types
export type {
  RumorManagementReport,
  DetectionRing,
  PlatformMonitoring,
  AlertEscalation,
  AlertLevel,
  RumorSourceClassification,
  RumorVelocityClassification,
  RumorDemographicClassification,
  RumorDamageClassification,
  Tier1Protocol,
  Tier2Protocol,
  Tier3Protocol,
  Tier4Protocol,
  ResponseTimeSummary,
  FactCheckPipeline,
  FormatSelection,
  LanguageStrategy,
  ApprovalAuthority,
  DistributionChannel,
  PreBunkCategory,
  PreBunkingPhase,
  KnownRumorScenario,
  HistoricalIncidentPreBunk,
  FactCheckNetworkStructure,
  RegionalCoverageTarget,
  ExpertPanel,
  ResponseTimeMetric,
  ContainmentRateTarget,
  EngagementMetric,
  PreBunkingMetric,
  NetworkHealthMetric,
  PreElectionActivities,
  CampaignPhaseActivities,
  KeySuccessFactor,
  IntegrationPoint,
} from "@/types/rumor-management-types";

// Data
export {
  detectionRingsData,
  platformMonitoringData,
  alertEscalationData,
  alertLevelsData,
  sourceClassificationsData,
  velocityClassificationsData,
  demographicClassificationsData,
  damageClassificationsData,
  tier1ProtocolData,
  tier2ProtocolData,
  tier3ProtocolData,
  tier4ProtocolData,
  responseTimeSummaryData,
  factCheckPipelineData,
  formatSelectionData,
  languageStrategyData,
  approvalAuthorityData,
  distributionChannelsData,
  preBunkCategoriesData,
  preBunkingPhasesData,
  knownRumorScenariosData,
  historicalIncidentsData,
  networkStructureData,
  regionalCoverageTargetsData,
  expertPanelsData,
  responseTimeMetricsData,
  containmentRateTargetsData,
  engagementMetricsData,
  preBunkingMetricsData,
  networkHealthMetricsData,
  preElectionActivitiesData,
  campaignPhaseActivitiesData,
  keySuccessFactorsData,
  integrationPointsData,
  rumorManagementReport,
} from "@/lib/rumor-management-data";
