// Index file for Sentiment Analysis, Rumor Management & Influencer Mapping
// Re-exports all types and data for easier imports

// Types
export type {
  PrimaryEmotion,
  EmotionIntensity,
  EmotionDuration,
  AttributionType,
  TrustMetric,
  SentimentBaselineType,
  NSSRange,
  SVIComponent,
  VelocityThreshold,
  IssueSentiment,
  DemographicSentiment,
  RegionalSentiment,
  PlatformCoverage,
  SurveyType,
  FocusGroupType,
  MediaType,
  RumorType,
  PunjabRumorCategory,
  RumorLifecycleStage,
  SpreadOriginType,
  AmplifierType,
  DetectionChannel,
  VerificationStep,
  ResponseOption,
  LegalProvision,
  PlatformReporting,
  JournalistCategory,
  FormerPoliticianCategory,
  ReligiousAuthority,
  DeraInfo,
  CastePanchayatLeader,
  CelebrityCategory,
  GrassrootsLeadership,
  ProfessionalNetwork,
  InfluencerScoringComponent,
  AlignmentScoring,
  ActivityMetric,
  InfluencerTier,
  Influencer,
  InfluencerActivity,
  InfluencerRelationship,
} from "@/types/sentiment-analysis-types";

// Data
export {
  primaryEmotionsData,
  emotionIntensityData,
  emotionDurationData,
  attributionTypesData,
  trustMetricsData,
  sentimentBaselineTypesData,
  nssRangesData,
  sviComponentsData,
  velocityThresholdsData,
  issueSentimentsData,
  demographicSentimentsData,
  regionalSentimentsData,
  platformCoverageData,
  surveyTypesData,
  focusGroupTypesData,
  mediaTypesData,
  rumorTypesData,
  punjabRumorCategoriesData,
  rumorLifecycleStagesData,
  spreadOriginTypesData,
  amplifierTypesData,
  detectionChannelsData,
  verificationStepsData,
  responseOptionsData,
  legalProvisionsData,
  platformReportingData,
  journalistCategoriesData,
  formerPoliticianCategoriesData,
  religiousAuthoritiesData,
  deraInfoData,
  castePanchayatLeadersData,
  celebrityCategoriesData,
  grassrootsLeadershipData,
  professionalNetworksData,
  influencerScoringComponentsData,
  alignmentScoringsData,
  activityMetricsData,
  influencerTiersData,
} from "@/lib/sentiment-analysis-data";
