// Permanent Infrastructure Types - Index
// Re-exports all types from permanent-infrastructure-types for convenient importing

export {
  type PermanentInfrastructureMetadata,
  type VoterDatabaseAsset,
  type GisInfrastructureAsset,
  type NlpAnalyticsAsset,
  type MediaRelationshipAsset,
  type VolunteerManagementAsset,
  type DigitalMonitoringAsset,
  type CorePermanentAsset,
  type KnowledgeManagementSystem,
  type ActivityPeriod,
  type ActivityEntry,
  type ActivityCalendar,
  type OrganizationalRole,
  type OrganizationalStructure,
  type BudgetCategory,
  type BudgetEstimate,
  type RefreshCycle,
  type TechnologyAsset,
  type TechnologyRefreshCycle,
  type DPDPComplianceRequirements,
  type DPDPCompliancePosture,
  type RiskLikelihood,
  type RiskCategory,
  type RiskFactor,
  type RiskAssessment,
  type ImplementationPhase,
  type ImplementationRoadmap,
  type VerificationItem,
  type PermanentIntelligenceInfrastructure,
} from './permanent-infrastructure-types';
